### ISSUE TITLE
SLOW3D

### ISSUE THREAD

**Issue by x423xu** [tehret/vbm3d#3]
Dear sir， when I tried to make the project with DSLOW3D=1, it comes out the error that some variables were not declared in func 'temporal_transform(group_3D, prms.k, prms.kt, vid_noisy.sz.channels, nSx_r, plan_1d)', at line 1937 in vbm3d.cpp. For example, p, q, size and ht were not declared.

**Comment by tehret** [comment]
There was indeed a problem due to a partial commit. This has been fixed
